basePath: /
host: localhost:8000
info:
  contact:
    email: edsontofolo@gmail.com
    name: Edson Gustavo Tofolo
    url: http//github.com/EdsonGustavoTofolo
  description: Product API with authentication
  license:
    name: Edson License
    url: http//github.com/
  termsOfService: http://swagger.io/terms/
  title: Go Expert API Example
  version: 1.o
paths: {}
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
